os: 
  - osx
  - linux
  - windows
language: node_js
sudo: required
node_js:
  - "8"
before_install: if [[ "$TRAVIS_OS_NAME" != 'windows' ]]; then unset _JAVA_OPTIONS; fi
install:
  - npm install
script: 
  - npm run test
  - npm run size
branches:
  only:
    - master
cache:
  directories:
    - node_modules