os: 
  - osx
  - linux
  - windows
language: node_js
sudo: required
node_js:
  - 8
before_install:
  - unset _JAVA_OPTIONS  # JVM heap sizes break closure compiler
install:
  - npm install
script: 
  - npm run test
  - npm run size
branches:
  only:
    - master
cache:
  directories:
    - node_modules